[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.4"
name = "tet_utils"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
